# Generated by Django 4.0.1 on 2022-02-05 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Description', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(30)])),
                ('Number', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('bg_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('Image', models.ImageField(upload_to='static/uploads/country')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('dest_type', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('dest_price', models.IntegerField(validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('dest_desc', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('dest_location', models.CharField(max_length=120)),
                ('dest_image', models.ImageField(upload_to='static/uploads/destination', validators=[django.core.validators.URLValidator])),
                ('day_one', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('total_person', models.IntegerField(default=2)),
                ('day_two', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('day_three', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.country')),
            ],
        ),
    ]
