# Generated by Django 4.0.1 on 2022-02-05 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastname', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('profile_pic', models.FileField(default='static/images/user.png', upload_to='static/uploads/profile')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
